# Generated by Django 6.0.3 on 2026-04-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.IntegerField(blank=True, null=True)),
                ('inspection_type', models.CharField(choices=[('pickup', 'Départ (Prise en charge)'), ('return', 'Retour (Restitution)')], default='pickup', max_length=10)),
                ('image_input', models.ImageField(upload_to='inputs/')),
                ('image_output', models.ImageField(blank=True, null=True, upload_to='outputs/')),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
