# Generated by Django 6.0.3 on 2026-04-23 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('status', models.CharField(choices=[('excellent', 'Excellent État'), ('good', 'Bon État'), ('damaged', 'Dommages Détectés'), ('maintenance', 'En Maintenance')], default='excellent', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(default=1)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_card_photo', models.ImageField(upload_to='id_cards/')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('has_chauffeur', models.BooleanField(default=False, verbose_name='Chauffeur Privé (+150 DA/j)')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='Assurance Premium (+50 DA/j)')),
                ('has_gps', models.BooleanField(default=False, verbose_name='Pack WiFi & GPS HP (+20 DA/j)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='location_service.car')),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('pickup', 'Départ (Prise en charge)'), ('return', 'Retour (Restitution)')], default='pickup', max_length=10)),
                ('image_input', models.ImageField(upload_to='inputs/')),
                ('image_output', models.ImageField(blank=True, null=True, upload_to='outputs/')),
                ('result_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='location_service.car')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client')], default='client', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
