# Generated by Django 6.0.3 on 2026-04-24 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
