# Generated by Django 6.0.3 on 2026-03-29 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("license_plate", models.CharField(max_length=20, unique=True)),
                ("price_per_day", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image", models.ImageField(blank=True, null=True, upload_to="cars/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent État"),
                            ("good", "Bon État"),
                            ("damaged", "Dommages Détectés"),
                            ("maintenance", "En Maintenance"),
                        ],
                        default="excellent",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="inspection",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inspections",
                to="inspections.car",
            ),
        ),
    ]
