# Generated by Django 6.0.3 on 2026-03-29 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0002_car_inspection_car"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("duration_days", models.PositiveIntegerField(default=1)),
                ("phone_number", models.CharField(max_length=20)),
                ("id_card_photo", models.ImageField(upload_to="id_cards/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="inspections.car",
                    ),
                ),
            ],
        ),
    ]
