# Generated by Django 6.0.3 on 2026-03-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0003_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="inspection_type",
            field=models.CharField(
                choices=[
                    ("pickup", "Départ (Prise en charge)"),
                    ("return", "Retour (Restitution)"),
                ],
                default="pickup",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="inspection",
            name="result_json",
            field=models.JSONField(default=dict),
        ),
    ]
