# Generated by Django 5.2.12 on 2026-04-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
