# Generated by Django 6.0.4 on 2026-04-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inspections", "0008_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="has_chauffeur",
            field=models.BooleanField(
                default=False, verbose_name="Chauffeur Privé (+150 DA/j)"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="has_gps",
            field=models.BooleanField(
                default=False, verbose_name="Pack WiFi & GPS HP (+20 DA/j)"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="has_insurance",
            field=models.BooleanField(
                default=False, verbose_name="Assurance Premium (+50 DA/j)"
            ),
        ),
    ]
